version: '3.8'
services:
  db:
    image: mongo
    restart: always
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=raven
      - MONGO_INITDB_ROOT_PASSWORD=passwd

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=raven
      - ME_CONFIG_MONGODB_ADMINPASSWORD=passwd
      - ME_CONFIG_MONGODB_SERVER=db
    depends_on:
      - db


volumes:
  mongodb_data_container:

